remove qemu_2.%.bbappend: remove it
Workaround the error:
$ setup.sh --distro=wrlinux-std-sato --machine=qemux86 --dl-layers --all-layers
Initial a build
$ bitbake world -cfetchall

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'spice' (but /path/to/layers/oe-core/meta/recipes-devtools/qemu/qemu_2.10.0.bb DEPENDS on or otherwise requires it)
spice was skipped: Not supported in this configuration by Wind River.  To override, add to your local.conf: PNWHITELIST_cloud-services-layer += 'spice'
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'qemu', 'spice']

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>