spice: Fix compile errors from gcc 7 with spice 0.12.4
../../git/server/red_parse_qxl.c:367:18: error: 'BITMAP_FMT_IS_RGB' defined but not used [-Werror=unused-const-variable=]
 static const int BITMAP_FMT_IS_RGB[] = {0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1};
                  ^~~~~~~~~~~~~~~~~
../../git/server/inputs_channel.c: In function 'inputs_channel_handle_parsed':
../../git/server/inputs_channel.c:317:38: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case SPICE_MSGC_INPUTS_KEY_DOWN: {
                                      ^
../../git/server/inputs_channel.c:324:5: note: here
     case SPICE_MSGC_INPUTS_KEY_UP: {
     ^~~~
../../git/server/reds.c: In function 'vdi_port_read_one_msg_from_device':
../../git/server/reds.c:797:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
             state->read_state = VDI_PORT_READ_STATE_GET_BUFF;
             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../git/server/reds.c:798:9: note: here
         case VDI_PORT_READ_STATE_GET_BUFF: {
         ^~~~
../../git/server/reds.c:807:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
             state->read_state = VDI_PORT_READ_STATE_READ_DATA;
             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../git/server/reds.c:809:9: note: here
         case VDI_PORT_READ_STATE_READ_DATA:
         ^~~~

This patch just adds the fallthrough comments which are already
checked in upstream along with the removal of the static variable
which is not used.

The newer versions of spice already have this fixed, so there is no
need to further upstream this patch.  It gets dropped in the future.

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>